#!/usr/bin/env python3
""" 13-regex_filter """

from pymongo import MongoClient

def regex_filter():
    """
    Lists all documents with name starting with 'Holberton' in the collection school.
    """
    client = MongoClient('mongodb://127.0.0.1:27017')
    db = client.my_db
    collection = db.school

    cursor = collection.find({"name": {"$regex": "^Holberton"}})
    for document in cursor:
        print(document)

if __name__ == "__main__":
    regex_filter()
